### ISSUE TITLE
Point others to the officially supported package

### ISSUE THREAD

**Issue by pavlindrom** [FlorianHockmann/Gremlin.Net#15]
I have happened across this repo when I was looking for a good .NET package to query gremlin queries with, and I thought that this is the state of art in .NET - but today a coworker opened my eyes to the official implementation, so I wonder if the readme can be updated to point people over to that: https://github.com/apache/tinkerpop/tree/master/gremlin-dotnet

Thanks a lot!

**Comment by FlorianHockmann** [comment]
Yeah, I also wonder about the fact that this repo seems to be still rising in popularity although it isn't really maintained any more.

Do you think that a link to the source code in TinkerPop's repository is important? The README currently includes a note stating the fact that Gremlin.Net is now included in Apache TinkerPop with links to the Gremlin.Net section in the TinkerPop docs and to the TinkerPop homepage: https://github.com/FlorianHockmann/Gremlin.Net#current-state-gremlinnet-now-part-of-apache-tinkerpop

But I guess I could make this note stick out even more.

**Comment by pavlindrom** [comment]
I'm sorry, I see that it's all there! Ugh, I think I need to get better at reading documentation - or maybe for the likes of me, draw more attention to that paragraph (I think the work deprecated will catch eyeballs). I'll leave that at your discretion, feel free to close this issue!

**Comment by FlorianHockmann** [comment]
Thanks for the suggestion @pavlindrom. I hope the now README makes it more obvious that this isn't the right place any more to get information about Gremlin.Net.
