### ISSUE TITLE
JsonSerializerSettings can't be set

### ISSUE THREAD

**Issue by pnda489** [FlorianHockmann/Gremlin.Net#16]
Hi,

i saved a time in String UTC Format in the Cosmos GraphDB.
As "yyyy-MM-ddTHH:mm:ssZ"

As i retrieved it, i though i would come back as string but it comes back as DateTime.

Is think this comes from the NewtonJsoft SerializerSettings in the Gremlin.net

Is there any way to change this default Settings to my behavior?

I want to do something like this:

		    JsonConvert.DefaultSettings = () => new JsonSerializerSettings
		    {
		        DateParseHandling = DateParseHandling.None,
		        DateFormatString = "yyyy-MM-ddTHH:mm:ssZ"
		    };

Thanks!

**Comment by FlorianHockmann** [comment]
I just verified your problem with a simple unit test:

```cs
[Theory, MemberData(nameof(Versions))]
public void DeserializeDateTimeString(int version)
{
    var dateTime = DateTime.MinValue;
    var dateTimeString = dateTime.ToString("yyyy-MM-ddTHH:mm:ssZ");
    var graphSon = $"\"{dateTimeString}\"";
    var reader = CreateStandardGraphSONReader(version);

    var readValue = reader.ToObject(JToken.Parse(graphSon));

    Assert.Equal(dateTime, readValue);          // passes, but shouldn't
    Assert.Equal(dateTimeString, readValue);    // should pass, but fails due to a type mismatch
}
```
(`CreateStandardGraphSONReader` simply creates a GraphSON reader for version 2 or 3, so both can be tested.)

So, this is definitely something currently not possible with Gremlin.Net. I expected your approach to work to be honest as `JsonConvert.DefaultSettings` is a static property and should therefore also work for the deserialization of Gremlin.Net. I don't see why it doesn't work and I also don't know of another way to solve your problem directly.

Could you please create a ticket in [the TinkerPop issue tracker](https://issues.apache.org/jira/projects/TINKERPOP/issues)? Gremlin.Net is now part of Apache TinkerPop and therefore I don't really maintain this repository any more.
