### ISSUE TITLE
Support Username + Password

### ISSUE THREAD

**Issue by AndreSteenbergen** [FlorianHockmann/Gremlin.Net#8]
Some endpoints are secured using username password connections.

At this moment this is not yet supported by Gremlin.Net.

**Comment by AndreSteenbergen** [comment]
I seem to have an old version. Sorry.

**Comment by FlorianHockmann** [comment]
Basic authentication was included in `master` (thanks to #7), but I hadn't published a package with that change until today: https://www.nuget.org/packages/Gremlin.Net/0.2.0
