### ISSUE TITLE
Target .NET Framework 4.5

### ISSUE THREAD

**Issue by FlorianHockmann** [FlorianHockmann/Gremlin.Net#9]
Gremlin.Net currently only targets .NET Standard 1.3 which is supported by .NET Framework 4.6 and higher. Since many users still use .NET Framework 4.5, it would be a good idea to also target that framework to make Gremlin.Net accessible to those users.

The reason why Gremlin.Net currently doesn't target anything below .NET Standard 1.3 was that some of its dependencies like [`System.Net.WebSockets`](https://www.nuget.org/packages/System.Net.WebSockets/) only target that version (and the respective .NET Framework 4.6). But since these dependencies where already part of .NET Framework 4.5, it should be possible to add that as a target framework and not use these NuGet packages for that target.

**Comment by FlorianHockmann** [comment]
I just published version 0.2.1 with support for .NET Framework 4.5. Would be great to hear from you guys @aaronlangford31 and @ChrisMiskowiec if that solves your problem. Then I can close this issue.

**Comment by ChrisMiskowiec** [comment]
@FlorianHockmann Worked for me! I am now able to install the package in my .NET 4.5 projects, thanks!

**Comment by FlorianHockmann** [comment]
Good to know that it solved your problem.
